/** @type {import('tailwindcss').Config} */
export default {
  // Prefix for all utility classes: ds-flex, ds-bg-primary-500, etc.
  prefix: 'ds-',

  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],

  theme: {
    extend: {
      // Map Tailwind color utilities to the DS CSS variables.
      // This way, swapping a theme (data-theme="black-friday") automatically
      // repaints every component that uses ds-bg-primary-500, ds-text-error-500, etc.
      colors: {
        primary: {
          25: 'var(--ds-color-primary-25)',
          50: 'var(--ds-color-primary-50)',
          100: 'var(--ds-color-primary-100)',
          200: 'var(--ds-color-primary-200)',
          300: 'var(--ds-color-primary-300)',
          400: 'var(--ds-color-primary-400)',
          500: 'var(--ds-color-primary-500)',
          600: 'var(--ds-color-primary-600)',
          700: 'var(--ds-color-primary-700)',
          800: 'var(--ds-color-primary-800)',
          900: 'var(--ds-color-primary-900)',
        },
        secondary: {
          25: 'var(--ds-color-secondary-25)',
          50: 'var(--ds-color-secondary-50)',
          100: 'var(--ds-color-secondary-100)',
          200: 'var(--ds-color-secondary-200)',
          300: 'var(--ds-color-secondary-300)',
          400: 'var(--ds-color-secondary-400)',
          500: 'var(--ds-color-secondary-500)',
          600: 'var(--ds-color-secondary-600)',
          700: 'var(--ds-color-secondary-700)',
          800: 'var(--ds-color-secondary-800)',
          900: 'var(--ds-color-secondary-900)',
        },
        neutral: {
          25: 'var(--ds-color-neutral-25)',
          50: 'var(--ds-color-neutral-50)',
          100: 'var(--ds-color-neutral-100)',
          200: 'var(--ds-color-neutral-200)',
          300: 'var(--ds-color-neutral-300)',
          400: 'var(--ds-color-neutral-400)',
          500: 'var(--ds-color-neutral-500)',
          600: 'var(--ds-color-neutral-600)',
          700: 'var(--ds-color-neutral-700)',
          800: 'var(--ds-color-neutral-800)',
          900: 'var(--ds-color-neutral-900)',
        },
        success: {
          50: 'var(--ds-color-success-50)',
          100: 'var(--ds-color-success-100)',
          200: 'var(--ds-color-success-200)',
          300: 'var(--ds-color-success-300)',
          400: 'var(--ds-color-success-400)',
          500: 'var(--ds-color-success-500)',
          600: 'var(--ds-color-success-600)',
          700: 'var(--ds-color-success-700)',
          800: 'var(--ds-color-success-800)',
          900: 'var(--ds-color-success-900)',
        },
        warning: {
          50: 'var(--ds-color-warning-50)',
          100: 'var(--ds-color-warning-100)',
          200: 'var(--ds-color-warning-200)',
          300: 'var(--ds-color-warning-300)',
          400: 'var(--ds-color-warning-400)',
          500: 'var(--ds-color-warning-500)',
          600: 'var(--ds-color-warning-600)',
          700: 'var(--ds-color-warning-700)',
          800: 'var(--ds-color-warning-800)',
          900: 'var(--ds-color-warning-900)',
        },
        error: {
          50: 'var(--ds-color-error-50)',
          100: 'var(--ds-color-error-100)',
          200: 'var(--ds-color-error-200)',
          300: 'var(--ds-color-error-300)',
          400: 'var(--ds-color-error-400)',
          500: 'var(--ds-color-error-500)',
          600: 'var(--ds-color-error-600)',
          700: 'var(--ds-color-error-700)',
          800: 'var(--ds-color-error-800)',
          900: 'var(--ds-color-error-900)',
        },
        'bg-base': 'var(--ds-color-bg-base)',
        'bg-subtle': 'var(--ds-color-bg-subtle)',
        'bg-emphasis': 'var(--ds-color-bg-emphasis)',
        'surface-base': 'var(--ds-color-surface-base)',
        'surface-raised': 'var(--ds-color-surface-raised)',
        'surface-overlay': 'var(--ds-color-surface-overlay)',
        'sidebar-base': 'var(--ds-color-sidebar-base)',
        'sidebar-foreground': 'var(--ds-color-sidebar-foreground)',
        'sidebar-primary': 'var(--ds-color-sidebar-primary)',
        'sidebar-primary-foreground': 'var(--ds-color-sidebar-primary-foreground)',
        'sidebar-accent': 'var(--ds-color-sidebar-accent)',
        'sidebar-accent-foreground': 'var(--ds-color-sidebar-accent-foreground)',
        'sidebar-border': 'var(--ds-color-sidebar-border)',
        'sidebar-ring': 'var(--ds-color-sidebar-ring)',
        'chart-1': 'var(--ds-color-chart-1)',
        'chart-2': 'var(--ds-color-chart-2)',
        'chart-3': 'var(--ds-color-chart-3)',
        'chart-4': 'var(--ds-color-chart-4)',
        'chart-5': 'var(--ds-color-chart-5)',
      },
      borderRadius: {
        none: 'var(--ds-radius-none)',
        xs: 'var(--ds-radius-xs)',
        sm: 'var(--ds-radius-sm)',
        md: 'var(--ds-radius-md)',
        lg: 'var(--ds-radius-lg)',
        full: 'var(--ds-radius-full)',
      },
      boxShadow: {
        sm: 'var(--ds-shadow-sm)',
        md: 'var(--ds-shadow-md)',
        lg: 'var(--ds-shadow-lg)',
      },
      fontFamily: {
        sans: 'var(--ds-font-family)',
      },
      fontSize: {
        10: 'var(--ds-font-size-10)',
        12: 'var(--ds-font-size-12)',
        14: 'var(--ds-font-size-14)',
        16: 'var(--ds-font-size-16)',
        18: 'var(--ds-font-size-18)',
        20: 'var(--ds-font-size-20)',
        24: 'var(--ds-font-size-24)',
        32: 'var(--ds-font-size-32)',
        40: 'var(--ds-font-size-40)',
        56: 'var(--ds-font-size-56)',
      },
      fontWeight: {
        regular: 'var(--ds-font-weight-regular)',
        medium: 'var(--ds-font-weight-medium)',
        semibold: 'var(--ds-font-weight-semibold)',
        bold: 'var(--ds-font-weight-bold)',
        extrabold: 'var(--ds-font-weight-extrabold)',
      },
      lineHeight: {
        16: 'var(--ds-line-height-16)',
        18: 'var(--ds-line-height-18)',
        20: 'var(--ds-line-height-20)',
        26: 'var(--ds-line-height-26)',
        32: 'var(--ds-line-height-32)',
        42: 'var(--ds-line-height-42)',
        52: 'var(--ds-line-height-52)',
        68: 'var(--ds-line-height-68)',
      },
    },
  },

  plugins: [],
};
