apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "design-system.fullname" . }}
  labels:
    {{- include "design-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "design-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Files.Get ".env" | sha256sum }}
      labels:
        {{- include "design-system.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "design-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: envfile-volume
            mountPath: ./usr/src/app/.env
            subPath: .env
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: "{{ .Values.ddtrace.service }}"
            - name: DD_ENV
              value: "{{ .Values.ddtrace.env }}"
            - name: DD_VERSION
              value: "{{ .Values.ddtrace.version }}"
            - name: DD_LOGS_INJECTION
              value: "false"
            - name: DD_TRACE_CLI_ENABLED
              value: "false"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: envfile-volume
        configMap:
          name: envfile
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
