apiVersion: v1
kind: Service
metadata:
  name: {{ include "design-system.fullname" . }}
  labels:
    {{- include "design-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "design-system.selectorLabels" . | nindent 4 }}
